### PR TITLE
Fix dependencies and add tests

### PR DESCRIPTION
**Pull request by jgeralnik**
Just a getting started PR. First I fixed the environment so it could run on my computer - there were some important dependencies missing (most importantly Django itself), a hardcoded `alona` path, and a hardcoded db password that I prefer not to use myself.

Next (and this should be a separate PR but it's small enough that it shouldn't matter) I think the implementation of the algorithm is a bit complex and would like to simplify it, but before touching it I added some tests so we can at least see the current behavior and make sure we're not breaking anything.

### CODE REVIEW

**Comment by jgeralnik** [comment]
@alonaviv

**Comment by alonaviv** [comment]
@jgeralnik This is awesome! Thank you! I'm very happy you've added some tests for the algorithm, I've been nervous that they don't exist yet. I just recently changed the whole algorithm and implementation, after researching how various Karaoke runners do it. Happy to hear/see your suggestions to improve and simplify it. If you want we can do a zoom call or something.
And as you see I never planned for others to be able to collaborate - I'm glad you made it possible. Of course the DB password is only for running locally - production replaces it (and other settings) with the `local_settings` file

**Comment by alonaviv** [comment]
Oh and weird about the dependencies.. I think I did pip freeze from my environment.. I'll later compare the new requirements file with my freeze to see that nothing else is missing.

**Comment by jgeralnik** [comment]
I had some thoughts on improving the algorithm, I wrote it up and simulated and the results were... not so good. It would be interesting for the simulation to get a better idea of arrival times and song times, I made the arbitrary assumption that a new singer shows up every 5 minutes and songs take 3 minutes but throwing in some real data would allow better assessing changes.

On the other hand the current algorithm is probably good enough for now - I don't love that the position of all songs changes every time a new song is added, but after the first 10 songs it shouldn't be a huge issue. There's also a bug if there are less than 10 singers signed up before the tenth song that we should fix but that's a separate issue.

**Comment by alonaviv** [comment]
I finally had some time to think about your proposals. It's great to have another eye on this. Thank you!!!!!

I do think stability is important, and especially the UI needs to make it way more clear to everyone what the song list is.
Part of that is to implement my own UI instead of lazily directing to the django back-office like I've done so far. I think placeholders are an excellent idea - instead of adding them 2 by 2 in the second cycle, only adding each time a new singer comes along, I'll leave a placeholder and fill up the whole 2nd cycle immediately, and then just assign new singers to the placeholders.
And with the third cycle, right now it comes out of nowhere only when the 2nd cycle ends. I can leave a large "block" placeholder where all the new late singers will get priority, and then I can already populate the 3rd cycle as well.

About the 1st cycle, I'm thinking about what you said. As far as fairness goes, I don't think it's that important that the early arrivals get to sing an extra song there. If we have ABC, A just finished singing so it becomes BCA, and then D arrives, according to the Disneyland algorithm, It'll be BCAD - even though D arrived while B is singing. I think it's fair that D sings after C. He's already there and waited for two songs. 

My assumption is that people come in and sign up with an "infinite" amount of songs right away. So it's not about signing up with a new song after you're done- only deciding what the order of singers should be. The assumption is that everyone always has more songs they would like (and if not I skip them in `calculate_positions`).

But that's not actually my main concern - I can see the fairness point in both directions. What I'm concerned about is being in control of the timing of the evening. We run for 4 hours, and want to close the signup about an hour before we're done. With the current implementation, that happens after the last song of cycle 2 is sung. 

So the evening goes like this:
cycle 1: 10 songs (roughly an hour)
cycle 2: 20 songs (roughly two hours)
cycle 3: last hour, whatever we manage.

Worked out pretty well timing-wise in the two events we've done so far with this new algorithm. 

So - if we use the Disneyland style in the first cycle, the question is if the 2nd cycle should start after 10 singers or 10 songs. 
If we move to cycle 2 after 10 songs, there may be say only 5 singers that showed up by then (and looped twice). So cycle 2 becomes only 10 songs, and we'll close the signup way too early.
If we move to cycle 2 after 10 singers, and again it's a slow start and the few early comers kept singing, we could end up with say 17 songs in cycle 1. We'll still have 20 songs in cycle 2 but we may have started cycle 2 really late, which means we'll close the sign-up too late and won't be able to let the new late-comers sing their one song.

So I'm not able to see a way to implement the Disneyland algorithm for cycle 1 and keep our timing.
We could, as you suggested, control the cycle flow ourselves and not hard code it - but I'm not sure how that helps. We want (I think) to move to cycle 2 after an hour anyway, and it'll be a problem if cycle 2 ends up too small. 
It will indeed be better to have the program count 1 hour instead of 10 songs, but for now let's assume 10 songs is an hour - it's pretty close and this improvement won't change that much.
You said something about not hard-coding the length of cycle 2. How? The point is to repeat cycle 1 with new people in between. If we switch to cycle 3 too soon it won't let the cycle 1 people sing their second song.

My alternative that I tried to implement is the subcycle method. If you're in a sub-cycle, you're there temporarily. If someone new comes in he'll push you down, so eventually there will be 10 new people in the cycle. And if you managed to stay in the list until they come, you'll get to sing. I need to find a good UX solution to communicate this.
Not ideal at all, since it'll erase you from the list after someone new came, even if you've already sung. If I decide to continue this way, I need to think of way to make it better. 

I thought of maybe only adding the next repeating singer if the list is completely empty. What do you think of this solution? Basically, you won't ever see your name in the first cycle twice - unless the list is empty and then you get a surprise freebie, without previous notice. Now that I'm writing this, I might be for this option, since I don't actually think we've gotten to that position - new people always file in during the first few songs, and if there are only 3 people or so at the start they don't want to sing to themselves anyway. They wait for more people to show. So it's rare event - maybe it's right to tackle it this way. What do you think?

About the bug - I see a bug that it loops over the people in the cycle, even if they don't have a second song. So if we have ABCDE, and D,E signed up with one song, the list of songs will be ABCDEABC, and won't loop back over to AB again, even though they are the only ones left with songs. So the evening will halt if no one else signs up.
Is this what you meant? Not that I intentionally left songs that aren't in the cycle as being without priority - until they are assigned. In your first test, instead of the break I changed the query to:
`all_songs = SongRequest.objects.filter(position__isnull=False).order_by("position").all()`

Would love to hear what you think about all of this. @jgeralnik

**Comment by jgeralnik** [comment]
After being at the last night where your algorithm was used I'm actually really happy with it.

The timing was really great. It seemed very fair and Disneyland was unnecessary. Honestly even subcycles was irrelevant because of how fast new singers showed up as soon as things got started. I would eliminate it completely and in the rare case that 10 people don't show up before the queue is empty jump to priority 12 (the second song of cycle 2) and backfill mixed slots as singers arrive. Again this is unlikely to actually happen so will just show a more realistic idea of when your next song will be

I added you on FB, let's pivot the conversation from there to whatsapp and from there to zoom

**Pull request merged**
